DEFAULT_DATETIME_FORMAT = "%H:%M:%S - %d.%m.%y"

DIR_VISUALIZATION_REPORTS = "reports/"
DATE_FORMAT_TRACKING = "%H-%M_%d-%m-%y"
EXTENSION = "csv"

LOCATION_VISUALIZATION_REPORT = DIR_VISUALIZATION_REPORTS + DATE_FORMAT_TRACKING
