DEFAULT_DATETIME_FORMAT = "%H:%M:%S - %d.%m.%y"

DIR_VISUALIZATION_REPORTS = "reports/"
DATE_FORMAT_TRACKING = "%d-%m-%y_%H-%M"
EXTENSION = "csv"

LOCATION_VISUALIZATION_REPORT = DIR_VISUALIZATION_REPORTS + DATE_FORMAT_TRACKING
